// Lightweight i18n implementation - no external packages needed
import { createContext, useContext } from 'react';

export type Language = 'EN' | 'FR';

export const translations = {
    EN: {
        // Sidebar / Nav
        dashboard: "Dashboard",
        pipeline: "Pipeline",
        leads: "Leads",
        contacts: "Contacts",
        tourPackages: "Tour Packages",
        whatsapp: "WhatsApp",
        analytics: "Analytics",
        staff: "Staff",
        settings: "Settings",
        signout: "Sign Out",

        // Dashboard
        overview: "Overview of your agency's performance.",
        newLead: "New Lead",
        newTour: "New Tour",
        broadcast: "Broadcast",
        totalLeads: "Total Leads",
        activeTours: "Active Tours",
        conversionRate: "Conversion Rate",
        revenue: "Revenue",
        pendingFollowUps: "Pending Follow-ups",
        wonLeads: "Won Leads",
        avgBudget: "Avg. Budget",
        lostLeads: "Lost Leads",
        leadsTrend: "Leads Trend (Last 30 Days)",
        revenueByPackage: "Revenue by Package",
        recentActivity: "Recent Activity",
        system: "System",
        newLeadCreated: "New Lead Created",
        newTourAdded: "New Tour Added",
        addNewLeadTitle: "Add New Lead",
        addNewLeadDesc: "Add a new lead to your pipeline manually.",
        editLeadTitle: "Edit Lead",
        editLeadDesc: "Update the details of the lead.",

        // Pipeline
        manageSalesPipeline: "Manage your sales pipeline",
        import: "Import",
        export: "Export",
        newLeadsCol: "New Leads",
        contactedCol: "Contacted",
        qualifiedCol: "Qualified",
        proposalSentCol: "Proposal Sent",
        convertedCol: "Converted",
        lostCol: "Lost",

        // Leads Page
        leadsDesc: "Manage and track all your potential customers.",
        manageLeadsDesc: "Manage your leads list",
        searchLeads: "Search leads...",
        statusAll: "All Statuses",
        name: "Name",
        contact: "Contact",
        interestedTour: "Interested Tour",
        budget: "Budget",
        source: "Source",
        status: "Status",
        assignedTo: "Assigned To",
        created: "Created",

        // Staff Page
        staffMgmt: "Staff Management",
        staffDesc: "Manage team members, roles, and permissions.",
        addMember: "Add Member",
        staffSalesPerf: "Staff Sales Performance",
        leaderboard: "Staff Leaderboard",
        revenueDesc: "Revenue generated by each staff member from converted leads.",
        teamMembers: "Team Members",
        teamDesc: "A list of all staff members having access to the dashboard.",
        avatar: "Avatar",
        memberDetails: "Team Member",
        roleDept: "Role & Dept",
        contactDetails: "Contact Details",
        searchStaff: "Search Staff...",
        staffCol: "Staff Member",
        roleCol: "Role & Dept",
        contactCol: "Contact Info",
        actions: "Actions",
        noStaffFound: "No staff members found.",
        viewProfile: "View Profile",
        editDetails: "Edit Details",
        changeRole: "Change Role",
        deactivateAccount: "Deactivate Account",
        editStaffTitle: "Edit Staff Member",
        addStaffTitle: "Add New Staff Member",
        editStaffDesc: "Update the details of the staff member.",
        addStaffDesc: "Add a new member to your team.",

        // Tour Packages Page
        tourPackagesDesc: "Manage and view all available tour packages.",
        createPackage: "Create Package",
        searchTour: "Search by destination or package name...",
        priceLowHigh: "Price: Low to High",
        priceHighLow: "Price: High to Low",
        durationShortest: "Duration: Shortest",
        noToursFound: "No tour packages found matching your criteria.",

        // Analytics Page
        analyticsDesc: "Performance insights and reports",
        reports: "Reports",
        leadAnalytics: "Lead Analytics",
        whatsappAnalytics: "WhatsApp Analytics",

        // General
        edit: "Edit",
        delete: "Delete",
        save: "Save",
        cancel: "Cancel",
        search: "Search...",
        addLead: "Add Lead",
    },
    FR: {
        // Sidebar / Nav
        dashboard: "Tableau de Bord",
        pipeline: "Pipeline",
        leads: "Prospects",
        contacts: "Contacts",
        tourPackages: "Forfaits Touristiques",
        whatsapp: "WhatsApp",
        analytics: "Analytiques",
        staff: "Personnel",
        settings: "Paramètres",
        signout: "Se Déconnecter",

        // Dashboard
        overview: "Aperçu des performances de votre agence.",
        newLead: "Nouveau Prospect",
        newTour: "Nouveau Circuit",
        broadcast: "Diffusion",
        totalLeads: "Total Prospects",
        activeTours: "Circuits Actifs",
        conversionRate: "Taux de Conversion",
        revenue: "Revenus",
        pendingFollowUps: "Suivis en Attente",
        wonLeads: "Prospects Gagnés",
        avgBudget: "Budget Moyen",
        lostLeads: "Prospects Perdus",
        leadsTrend: "Tendance Prospects (30 Derniers Jours)",
        revenueByPackage: "Revenus par Forfait",
        recentActivity: "Activité Récente",
        system: "Système",
        newLeadCreated: "Nouveau Prospect Créé",
        newTourAdded: "Nouveau Circuit Ajouté",
        addNewLeadTitle: "Créer un Nouveau Prospect",
        addNewLeadDesc: "Ajouter manuellement un nouveau prospect au pipeline.",
        editLeadTitle: "Modifier le Prospect",
        editLeadDesc: "Mettre à jour les détails du prospect.",

        // Pipeline
        manageSalesPipeline: "Gérez votre pipeline de ventes",
        import: "Importer",
        export: "Exporter",
        newLeadsCol: "Nouveaux",
        contactedCol: "Contactés",
        qualifiedCol: "Qualifiés",
        proposalSentCol: "Proposition Envoyée",
        convertedCol: "Convertis",
        lostCol: "Perdus",

        // Leads Page
        leadsDesc: "Gérez et suivez tous vos clients potentiels.",
        manageLeadsDesc: "Gérez votre liste de prospects",
        searchLeads: "Rechercher des prospects...",
        statusAll: "Tous les statuts",
        name: "Nom",
        contact: "Contact",
        interestedTour: "Circuit Intéressé",
        budget: "Budget",
        source: "Source",
        status: "Statut",
        assignedTo: "Assigné à",
        created: "Créé le",

        // Staff Page
        staffMgmt: "Gestion du Personnel",
        staffDesc: "Gérer les membres de l'équipe, rôles et permissions.",
        addMember: "Ajouter Membre",
        staffSalesPerf: "Performance Ventes du Personnel",
        leaderboard: "Classement du Personnel",
        revenueDesc: "Revenus générés par chaque membre à partir des prospects convertis.",
        teamMembers: "Membres de l'Équipe",
        teamDesc: "Liste de tous les membres ayant accès au tableau de bord.",
        avatar: "Avatar",
        memberDetails: "Membre de l'Équipe",
        roleDept: "Rôle et Dépt",
        contactDetails: "Détails Contact",
        searchStaff: "Rechercher du personnel...",
        staffCol: "Membre du personnel",
        roleCol: "Rôle et Dépt",
        contactCol: "Infos Contact",
        actions: "Actions",
        noStaffFound: "Aucun membre du personnel trouvé.",
        viewProfile: "Voir le Profil",
        editDetails: "Modifier les Détails",
        changeRole: "Changer le Rôle",
        deactivateAccount: "Désactiver le Compte",
        editStaffTitle: "Modifier le Membre",
        addStaffTitle: "Ajouter un Nouveau Membre",
        editStaffDesc: "Mettre à jour les détails du membre du personnel.",
        addStaffDesc: "Ajouter un nouveau membre à votre équipe.",

        // Tour Packages Page
        tourPackagesDesc: "Gérez et affichez tous les forfaits touristiques disponibles.",
        createPackage: "Créer un Forfait",
        searchTour: "Rechercher par destination ou nom de forfait...",
        priceLowHigh: "Prix: Bas à Élevé",
        priceHighLow: "Prix: Élevé à Bas",
        durationShortest: "Durée: La Plus Courte",
        noToursFound: "Aucun forfait trouvé selon vos critères.",

        // Analytics Page
        analyticsDesc: "Aperçus des performances et rapports",
        reports: "Rapports",
        leadAnalytics: "Analytiques Prospects",
        whatsappAnalytics: "Analytiques WhatsApp",

        // General
        edit: "Modifier",
        delete: "Supprimer",
        save: "Enregistrer",
        cancel: "Annuler",
        search: "Rechercher...",
        addLead: "Ajouter Prospect",
    }
} as const;

export type TranslationKey = keyof typeof translations.EN;

export interface I18nContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: TranslationKey) => string;
}

export const I18nContext = createContext<I18nContextType>({
    language: 'EN',
    setLanguage: () => { },
    t: (key) => translations.EN[key],
});

export const useI18n = () => useContext(I18nContext);
